AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app
  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  DemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: demo-lambda
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

Outputs:
  DemoFunction:
    Description: 'Demo Lambda Function ARN'
    Value: !GetAtt DemoFunction.Arn
  DemoFunctionIamRole:
    Description: 'Implicit IAM Role created for Demo function'
    Value: !GetAtt DemoFunction.Arn
